## Numpy Notes

In [3]:
import numpy as np

# Finding dimensions
a = np.array([[[1,0],[0,1]],[[1,2],[3,4]]])
print(a.ndim) 

3


In [4]:
type(a)

numpy.ndarray

In [6]:
print(a[1][0][1])

2


In [7]:
a.shape

(2, 2, 2)

In [9]:
a.nbytes  # Space taken by array 8 int x 4 bytes/int = 32 bytes

32

In [4]:
import numpy as np

# Reshaping arrays
x = np.arange(12)
print("Old array: \n", x)
y = x.reshape(4,3)
print("New array: \n", y)


Old array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
New array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


<b>Note: Slicing in numpy arrays merely generates pointer references to original array instead of creating a new array</b>

In [7]:
#Declaring lists
a = [0,1,2,3,4,5,6,7,8,9]
b = a[2:5]
b[1] = 99
print("Original list unchanged: ",a)
print("New list changed: ", b)

Original list unchanged:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
New list changed:  [2, 99, 4]


In [8]:
#Declaring numpy arrays
a = np.arange(10)
b = a[2:5]
b[1] = 99
print("New array changed: ", b)
print("Old array also changed:", a)

New array changed:  [ 2 99  4]
Old array also changed: [ 0  1  2 99  4  5  6  7  8  9]


<b>We can create a new array using the copy() function</b>

In [17]:
a = np.arange(10)
b = a[2:5].copy()
b[1] = 99
print("Original array unchanged: ",a)
print("New array changed: ", b)

Original array unchanged:  [0 1 2 3 4 5 6 7 8 9]
New array changed:  [ 2 99  4]


In [19]:
index = np.argwhere(a==4) #returns the indices with value 4
a[index] = -4
print(a)

[ 0  1  2  3 -4  5  6  7  8  9]


<b>Generating Randox matrix</b>

In [21]:
a = np.random.rand(4,3)
print(a)

[[0.07071    0.77290535 0.26652058]
 [0.75999655 0.36415824 0.10991264]
 [0.02772626 0.54164215 0.85765023]
 [0.27625404 0.16433267 0.39373655]]


In [22]:
#Rounding it to integers
a = np.round(10*a)
print(a)

[[1. 8. 3.]
 [8. 4. 1.]
 [0. 5. 9.]
 [3. 2. 4.]]


In [23]:
#Accessing ith row
i=2
print(a[i,:])

[0. 5. 9.]


In [25]:
#Accessing jth column
j=1
print(a[:,j])

[8. 4. 5. 2.]


In [26]:
#Accessing submatrix
print(a[1:3,0:2])

[[8. 4.]
 [0. 5.]]


In [27]:
print(a.T) #Taking transpose

[[1. 8. 0. 3.]
 [8. 4. 5. 2.]
 [3. 1. 9. 4.]]


<b>Linear algebra in Numpy</b>

In [31]:
import numpy.linalg as la
b = np.round(10*np.random.rand(3,3))
print("B matrix: \n", b)
print("B inverse: \n", la.inv(b))

B matrix: 
 [[ 0.  6.  2.]
 [ 5.  5.  2.]
 [ 9. 10.  3.]]
B inverse: 
 [[-0.17857143  0.07142857  0.07142857]
 [ 0.10714286 -0.64285714  0.35714286]
 [ 0.17857143  1.92857143 -1.07142857]]


In [32]:
#Sort columns
b.sort(axis=0)
print("sorted columns:  \n", b)

#Sort rows
b.sort(axis=1)
print("sorted rows: \n", b)

sorted columns:  
 [[ 0.  5.  2.]
 [ 5.  6.  2.]
 [ 9. 10.  3.]]
sorted rows: 
 [[ 0.  2.  5.]
 [ 2.  5.  6.]
 [ 3.  9. 10.]]


<b>Broadcasting</b>

In [33]:
#Instead of doing this
d = b + [[5,5,5],[5,5,5],[5,5,5]]
print("D: \n",d)
#We may just write
e = b+5
print("E: \n", e)

D: 
 [[ 5.  7. 10.]
 [ 7. 10. 11.]
 [ 8. 14. 15.]]
E: 
 [[ 5.  7. 10.]
 [ 7. 10. 11.]
 [ 8. 14. 15.]]


In [44]:
#This is called broadcasting as one scalar value is broadcasted onto an entire matrix having similar dimensions
#Another example
X = np.array([[1,2],[3,4]])
#If we want to add [[1,1],[2,2]], we may just add [1,2]
print(X+(np.arange(1,3).reshape(2,1)))

[[2 3]
 [5 6]]


<b>HSTACK, VSTACK, SORT</b>

In [49]:
A = np.round(10*np.random.rand(2,3))
print("Original A: \n", A)

B = np.round(10*np.random.rand(2,2))
print("Original B: \n", B)

C = np.round(10*np.random.rand(1,3))
print("Original C: \n", C)

#Concatenating horizontally
X = np.hstack((A,B))
print("Hstack: \n", X)

#Concatenating vertically
Y = np.vstack((A,C))
print("Vstack: \n", Y)

#Sorting
arr = np.array([2,4,5,1,3,8,0,6,9,7])
print("Sorted array: ", np.sort(arr))

Original A: 
 [[0. 9. 9.]
 [1. 4. 5.]]
Original B: 
 [[2. 9.]
 [3. 9.]]
Original C: 
 [[6. 9. 6.]]
Hstack: 
 [[0. 9. 9. 2. 9.]
 [1. 4. 5. 3. 9.]]
Vstack: 
 [[0. 9. 9.]
 [1. 4. 5.]
 [6. 9. 6.]]
Sorted array:  [0 1 2 3 4 5 6 7 8 9]


<b>Testing Speed</b>

In [54]:
b = np.random.rand(1000000)
%timeit sum(b)
%timeit np.sum(b)

81.8 ms ± 415 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.39 ms ± 112 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [55]:
#We can see how fast numpy's universal function is in summing up the values

#Let us see how much time it takes to sum using a for loop

def mySum():
    s=0
    for x in b:
        s+=x
    return s

%timeit mySum()

107 ms ± 888 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
#Numpy clearly is the fastest alternative